name: Trigger Jitpack Build
on:
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jitpack Build
        run: curl "https://jitpack.io/com/github/BridgeSplash/Immortal/${GITHUB_SHA:0:10}/build.log"
